### ISSUE TITLE
代码无法运行，错误信息在 (f'') 这种表达式上

### ISSUE THREAD

**Issue by achaoge** [kevinqqnj/sudo-dynamic-solve#4]
运行环境

`certifi        2018.4.16
chardet        3.0.4
click          6.7
Flask          1.0.2
Flask-Compress 1.4.0
gunicorn       19.8.1
idna           2.6
itsdangerous   0.24
Jinja2         2.10
MarkupSafe     1.1.1
numpy          1.14.4
pip            20.2.3
requests       2.18.4
setuptools     47.1.0
urllib3        1.24.2
Werkzeug       0.15.3
wheel          0.35.1`

错误信息
[error.log](https://github.com/kevinqqnj/sudo-dynamic-solve/files/5383842/error.log)

**Comment by kevinqqnj** [comment]
需要python3，你用的是python2.7
